spring.application.name=dispatcherservice
# No server port needed since it's a worker, but let's set it to 0 
# so it doesn't clash if Spring tries to start a web server.
server.port=0

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# The same queue name we used in the Ingestion Service
webhook.queue.name=webhook.processing.queue

# The URL of your Audit Service (We'll use Eureka for this later!)
audit.service.url=http://localhost:8083/api/logs
