spring.application.name=ingestion-service
# Run the Ingestion Service on a different port so it doesn't clash with the Audit Service
server.port=8081

# Tell Spring Boot how to talk to your Docker RabbitMQ container
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# A custom name for our queue
webhook.queue.name=webhook.processing.queue
